language: python

python:
  - "3.6"

install:
 - pip install -r requirements.txt 
 - pip install coveralls codecov

script:
 - pytest --cov-report=term-missing --cov=app
 - python -m coverage report -m
 - coverage run --source app -m pytest

after_success:
 - coveralls.